
services:
  petclinic:
    image: wishnu21/petclinic-app:0.0.4
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.aws
      target: production
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://petclinic.czu2k8oa2fg5.us-east-2.rds.amazonaws.com/petclinic
    volumes:
      - ./:/app

    

volumes:
  mysql_data:
  mysql_config:
