
services:
  petclinic:
    image: wishnu21/petclinic-rest:0.0.2
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.aws
      target: production
    ports:
      - 8000:8000
      - 9966:9966
    environment:
      - SERVER_PORT=9966
      - MYSQL_URL=jdbc:mysql://petclinic.czu2k8oa2fg5.us-east-2.rds.amazonaws.com/petclinic
    volumes:
      - ./:/app

    

volumes:
  mysql_data:
  mysql_config:
